name: CICD

on:
  workflow_dispatch:
  pull_request:
    branches: ["prod"]

jobs:
  call-workflow:
    uses: rosalesponcerdev/workflow_repository/.github/workflows/docker-nginx-ci.yml@v1.1
    secrets: inherit
