name: CICD

on:
  workflow_dispatch:
  push:
    branches: ["prod"]

jobs:
  call-workflow:
    uses: rosalesponcerdev/workflow_repository/.github/workflows/docker-nginx.yml@v1.1
    secrets: inherit
